import type { ElsaStudioModuleApi } from "@elsa-workflows/studio-sdk";
import type { AttentionItem, AttentionSeverity } from "./attentionApi";
export interface AttentionSnooze { contributorId: string; itemId: string; generation: string; severity: AttentionSeverity; snoozedUntil: string; }
export interface AttentionPreferences { snoozes: AttentionSnooze[]; }
export function isSnoozed(item: AttentionItem, snoozes: AttentionSnooze[], now = Date.now()) { const match = snoozes.find(value => value.contributorId === item.contributorId && value.itemId === item.id); return !!match && Date.parse(match.snoozedUntil) > now && match.generation === item.generation && rank(item.severity) >= rank(match.severity); }
export function snooze(item: AttentionItem, durationMs: number, now = Date.now()): AttentionSnooze { return { contributorId: item.contributorId, itemId: item.id, generation: item.generation, severity: item.severity, snoozedUntil: new Date(now + durationMs).toISOString() }; }
export class AttentionPreferenceStore { private revision?: string; constructor(private api: ElsaStudioModuleApi, private hostId: string, private scopeKey: string, private anonymous = false) {} async load(): Promise<AttentionPreferences> { if (!this.anonymous) try { const doc = await this.api.backend.http.getJson<{ revision?: string; value: AttentionPreferences }>("/_elsa/studio/preferences/attention", { headers: { "X-Elsa-Studio-Host-Id": this.hostId } }); this.revision = doc.revision; return doc.value; } catch { /* device fallback */ } return this.local(); } async save(value: AttentionPreferences) { if (!this.anonymous) try { const doc = await this.api.backend.http.putJson<{ revision?: string }>("/_elsa/studio/preferences/attention", { schemaVersion: 1, value }, { headers: { "X-Elsa-Studio-Host-Id": this.hostId, ...(this.revision ? { "If-Match": `"${this.revision}"` } : { "If-None-Match": "*" }) } }); this.revision = doc.revision; return; } catch (error) { if (status(error) === 409 || status(error) === 412) throw error; } try { localStorage.setItem(this.key(), JSON.stringify(value)); } catch { /* best effort */ } } private key() { return `elsa-studio:attention:${this.scopeKey}`; } private local() { try { const value = localStorage.getItem(this.key()); return value ? JSON.parse(value) as AttentionPreferences : { snoozes: [] }; } catch { return { snoozes: [] }; } } }
function status(error: unknown) { return error instanceof Error ? (error as Error & { status?: number }).status : undefined; }
function rank(value: AttentionSeverity) { return value === "critical" ? 0 : value === "warning" ? 1 : 2; }
