packages:
  - "src/Elsa.Studio.Web/Client"
  - "src/Elsa.Studio.Web/StudioUi"
  - "src/Elsa.Studio.ConsoleStream/Client"
  - "src/Elsa.Studio.Diagnostics.OpenTelemetry/Client"
  - "src/Elsa.Studio.Diagnostics.StructuredLogs/Client"
  - "src/Elsa.Studio.CodeEditor/Client"
  - "src/Elsa.Studio.ExpressionEditors.JavaScript/Client"
  - "src/Elsa.Studio.ExpressionEditors.Liquid/Client"
  - "src/Elsa.Studio.FeatureManagement/Client"
  - "src/Elsa.Studio.Secrets/Client"
  - "src/Elsa.Studio.Weaver.Workflows/Client"
  - "src/Elsa.Studio.Workflows/Client"
  - "src/Elsa.Studio.Samples.Dashboard/Client"
  - "src/Elsa.Studio.Samples.WeatherForecast/Client"
allowBuilds:
  esbuild: set this to true or false
onlyBuiltDependencies:
  - esbuild
verifyDepsBeforeRun: false
