import React from "react";
import type { StudioDashboardWidgetBodyProps } from "@elsa-workflows/studio-sdk";
import type { RunHealthSettings, WorkflowRunHealthSnapshot } from "./workflowDashboardApi";
export function WorkflowRunHealthWidget({ snapshot, settings }: StudioDashboardWidgetBodyProps<WorkflowRunHealthSnapshot, RunHealthSettings>) {
  if (!snapshot) return null;
  if (snapshot.status === "unavailable") return <div className="workflow-dashboard-unavailable" role="status">Run statistics are unavailable{snapshot.errorCode ? ` (${snapshot.errorCode})` : ""}.</div>;
  const maximum = Math.max(1, ...snapshot.buckets.map(bucket => bucket.startedCount));
  return <div className="workflow-run-health"><div className="workflow-run-kpis"><Kpi label="Started" value={snapshot.startedCount}/><Kpi label="Succeeded" value={snapshot.succeededCount}/><Kpi label="Failed" value={snapshot.failedCount} detail={`${snapshot.failurePercentage}%`}/><Kpi label="Incident-bearing" value={snapshot.incidentBearingRunCount} detail={`${snapshot.incidentBearingPercentage}%`}/><Kpi label="Incidents" value={snapshot.incidentCount}/><Kpi label="Running now" value={snapshot.runningCount}/></div>{settings.includeTestRuns ? <p className="workflow-dashboard-notice">Includes transient test runs.</p> : null}<div className="workflow-run-trend" aria-label="Run health trend">{snapshot.buckets.map(bucket => { const failedShare = bucket.startedCount ? bucket.failedCount / bucket.startedCount * 100 : 0; const label = `${bucket.from} to ${bucket.to}: ${bucket.startedCount} started, ${bucket.failedCount} failed, ${bucket.incidentBearingRunCount} incident-bearing`; return <div key={bucket.from} role="img" aria-label={label} title={label} style={{ height: `${Math.max(4, bucket.startedCount / maximum * 100)}%` }}><span style={{ height: `${failedShare}%` }}/></div>; })}</div><section><h4>Highest-failure workflows</h4>{snapshot.highestFailureDefinitions.length ? <ol>{snapshot.highestFailureDefinitions.map(item => <li key={item.definitionId}><span>{item.name ?? item.definitionId}</span><strong>{item.failedCount}</strong></li>)}</ol> : <p>No failed workflows in this range.</p>}</section></div>;
}
function Kpi({label,value,detail}:{label:string;value:number;detail?:string}) { return <div><strong>{value}</strong><span>{label}</span>{detail ? <small>{detail}</small>:null}</div>; }
